version: '3.8'
services:
  db:
    image: docker.io/library/postgres:16
    container_name: evfleetoptimizer-db
    environment:
      POSTGRES_USER: evfleet
      POSTGRES_PASSWORD: evfleetpw
      POSTGRES_DB: evfleetdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
